name: Python Unittest + Reporte XML

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar unittest y guardar en XML
        run: |
          mkdir -p test-results
          python -m xmlrunner discover -s tests -o test-results

      - name: Subir resultados como artefacto
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: unittest-resultados
          path: test-results

      - name: Anotar fallos en el PR
        uses: mikepenz/action-junit-report@v4
        if: always()  # Se ejecuta incluso si los tests fallan
        with:
          report_paths: 'test-results/*.xml'
