name: Python Tests + Coverage + Reportes

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests con cobertura
        run: |
          mkdir -p test-results
          coverage run -m xmlrunner discover -s tests -o test-results
          coverage xml -o coverage.xml
          coverage html -d coverage_html

      - name: Subir resultados como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            .coverage
            coverage.xml
            coverage_html
            test-results

      - name: Anotar errores de tests en el PR
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-results/*.xml'

      - name: Comentar cobertura en el PR
        if: always()
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.8
          thresholdNew: 0.9
          thresholdModified: 0.5

      - name: Escaneo SonarQube
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
