name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Configuración de Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage

      # 4. Ejecutar tests y generar el reporte de cobertura
      - name: Ejecutar tests y generar cobertura
        run: |
          coverage run -m pytest
          coverage html -d coverage_html

      # 5. Subir el reporte de cobertura como artefacto
      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura-html
          path: coverage_html
