name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install coverage pytest-github-actions-annotate-failures

      - name: Ejecutar tests con anotaciones y generar cobertura
        run: |
          coverage run -m pytest --tb=short --annotate-failures
          coverage html -d coverage_html
          coverage xml -o coverage.xml

      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura-html
          path: coverage_html

      - name: Añadir comentario con cobertura al PR
        uses: romeovs/coverage-comment-action@v1
        with:
          coverage-file: coverage.xml
