name: Python Unittest + Cobertura + PR Anotaciones

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests con cobertura
        run: |
          mkdir -p test-results
          coverage run -m xmlrunner discover -s tests -o test-results || true
          coverage xml -o coverage.xml || true
          coverage html -d coverage_html || true

      - name: Subir reportes como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reportes
          path: |
            test-results
            coverage_html

      - name: Anotar errores de tests en el PR
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'test-results/*.xml'

      - name: Comentar cobertura en el PR
        uses: orgoro/coverage@v3.2
        if: always()
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.8
          thresholdNew: 0.9
          thresholdModified: 0.5

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nicolas-castro92
            -Dsonar.projectKey=nicolas-castro92_python-artefactos